@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.github.itellijlover.Tournoi",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1245635613 { 
   	label=github
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1054665200 { 
   	label=itellijlover
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Equipe1473653858[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Equipe</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   eq1: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   eq2: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   num: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Fenetre1031646685[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Fenetre</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ListeTournois: JPanel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   bequipes: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   bmatchs: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   bparams: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   bresultats: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   btournois: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   btours: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   c: JPanel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   creerTournoi: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   deleteTournoi: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   details_trace: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   detailt_nbtours: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   detailt_nom: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   detailt_statut: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   eq_ajouter: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   eq_desc: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   eq_js: JScrollPane [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   eq_jt: JTable [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   eq_layout: BoxLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   eq_modele: AbstractTableModel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   eq_p: JPanel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   eq_supprimer: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   eq_valider: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   equipes_trace: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fen: CardLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   gt: JTextArea [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   label: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   list: JList&lt;String&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   match_bas: JPanel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   match_desc: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   match_js: JScrollPane [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   match_jt: JTable [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   match_layout: BoxLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   match_modele: AbstractTableModel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   match_p: JPanel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   match_statut: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   match_trace: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   match_valider: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   noms_tournois: Vector&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   resultats_bas: JPanel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   resultats_desc: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   resultats_js: JScrollPane [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   resultats_jt: JTable [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   resultats_layout: BoxLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   resultats_p: JPanel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   resultats_statut: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   resultats_trace: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   s: Statement [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   selectTournoi: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   statut_deft: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   statut_slect: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   t: Tournoi [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tournois_trace: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tours_ajouter: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tours_desc: JLabel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tours_js: JScrollPane [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tours_layout: BoxLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tours_p: JPanel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tours_rentrer: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tours_supprimer: JButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   tours_t: JTable [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tours_trace: boolean [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- majStatutM()</TD></TR>
<TR><TD ALIGN="LEFT" >+ majboutons()</TD></TR>
<TR><TD ALIGN="LEFT" >+ tracer_details_tournoi()</TD></TR>
<TR><TD ALIGN="LEFT" >+ tracer_select_tournoi()</TD></TR>
<TR><TD ALIGN="LEFT" >+ tracer_tournoi_equipes()</TD></TR>
<TR><TD ALIGN="LEFT" >+ tracer_tournoi_matchs()</TD></TR>
<TR><TD ALIGN="LEFT" >+ tracer_tournoi_resultats()</TD></TR>
<TR><TD ALIGN="LEFT" >+ tracer_tours_tournoi()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MatchM1473653858[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MatchM</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   eq1: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   eq2: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   idmatch: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   num_tour: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   score1: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   score2: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   termine: boolean [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Tournoi1031646685[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Tournoi</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dataeq: Vector&lt;Equipe&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   datam: Vector&lt;MatchM&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   id_tournoi: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   ideqs: Vector&lt;Integer&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >#   nt: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   st: Statement [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   statut: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   statuttnom: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ ajouterEquipe()</TD></TR>
<TR><TD ALIGN="LEFT" >+ ajouterTour(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ creerTournoi(s2: Statement): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteTournoi(s2: Statement, nomtournoi: String): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ genererMatchs()</TD></TR>
<TR><TD ALIGN="LEFT" >+ getEquipe(index: int): Equipe</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMatch(index: int): MatchM</TD></TR>
<TR><TD ALIGN="LEFT" >+ getMatchsToDo(nbJoueurs: int, nbTours: int): Vector&lt;Vector&lt;Match&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ majEquipe(index: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ majEquipes()</TD></TR>
<TR><TD ALIGN="LEFT" >+ majMatch()</TD></TR>
<TR><TD ALIGN="LEFT" >+ majMatch(index: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ mysql_real_escape_string(str: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ supprimerEquipe(ideq: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ supprimerTour()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Fenetre1031646685 -> Tournoi1031646685[label="t
[0..1]"];
Tournoi1031646685 -> Equipe1473653858[label="dataeq
[0..*]"];
Tournoi1031646685 -> MatchM1473653858[label="datam
[0..*]"];
    
}
@enduml